import { chromium } from "playwright";
import fs from "node:fs";
const OUT = "/tmp/verify-design/dash"; fs.mkdirSync(OUT, { recursive: true });
const BASE = "http://holy-cross.localhost:5199";
const b = await chromium.launch({ channel: "chrome", headless: true });
const page = await (await b.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
const errs = []; page.on("pageerror", e => errs.push(e.message));
await page.goto(`${BASE}/accounts`, { waitUntil: "networkidle" });
await page.getByPlaceholder("Enter your email").fill("admin@holy-cross.example.com");
await page.getByPlaceholder("Enter your password").fill("School@2025");
await page.getByRole("button", { name: "Login" }).click();
await page.waitForURL(u => !u.pathname.includes("/accounts"), { timeout: 20000 });
await page.goto(`${BASE}/overview`, { waitUntil: "networkidle" });
await page.waitForTimeout(2400);

const panel = page.getByRole("region", { name: "Action needed" });
console.log("panel present:", await panel.count() > 0);
const btn = panel.getByRole("button");
console.log("collapsed by default (no blocking rows):", await btn.getAttribute("aria-expanded"));
console.log("summary:", (await panel.innerText()).split("\n").slice(0, 4).join(" | "));
await page.screenshot({ path: `${OUT}/focus-collapsed.png`, clip: { x: 256, y: 60, width: 1024, height: 300 } });
// Hover opens it, the way the console's does.
await panel.hover();
await page.waitForTimeout(700);
console.log("expanded on hover:", await btn.getAttribute("aria-expanded"), "(hover opens without pinning)");
const cards = panel.locator("a[href]");
console.log("cards:", await cards.count());
await page.screenshot({ path: `${OUT}/focus-hover.png`, clip: { x: 256, y: 60, width: 1024, height: 380 } });
await btn.click();
await page.waitForTimeout(600);
console.log("after pressing Maximize:", await btn.getAttribute("aria-expanded"));
await page.screenshot({ path: `${OUT}/focus-open.png`, fullPage: true });
console.log("page overflow:", await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await page.setViewportSize({ width: 390, height: 900 });
await page.waitForTimeout(800);
console.log("phone overflow:", await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await page.screenshot({ path: `${OUT}/focus-phone.png`, fullPage: true });
console.log("errors:", errs.length); errs.forEach(e => console.log(" -", e));
await b.close();
